apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devopslalitharwate-sudo/argocd_kustomization
    targetRevision: main
    path: overlays/prod
  destination:
    namespace: guestbook-prod
